src/stcal/ramp_fitting/gls_fit.py, src/stcal/ramp_fitting/ols_fit.py, src/stcal/ramp_fitting/ramp_fit.py, src/stcal/ramp_fitting/ramp_fit_class.py, src/stcal/ramp_fitting/utils.py
To reduce data model dependency an internal ramp fit class has been added.   This has been tested against JWST unit and regression tests.  All tests pass.
Closes issue #24
=> Al-553: Reduced data model dependency

src/stcal/jump/__init__.py, src/stcal/jump/constants.py, src/stcal/jump/jump.py, src/stcal/jump/twopoint_difference.py
Modified jump code to be common code within STCAL. Modified DQ flags to be retrieved from either ROMANCAL or JWST. I still need to commit updated CHANGES.rst from a different PR, as it is in a different (ROMANCAL) repo. After this is merged, romancal unit tests will be filed under RCAL-114 .
=> Move common jump code to stcal (RCAL-152).

README.md
(this is just to check if docs build on PRs)
=> add rtd badge

.github/workflows/ci.yml, setup.cfg, tox.ini
Use Codecov's github action to upload coverage.
=> Fix codecov uploads

.github/workflows/ci.yml, tox.ini
Actually upload the measured coverage...
=> Report jwst-cov CI job to codecov

CHANGES.rst, src/stcal/saturation/saturation.py, tests/test_saturation.py
This PR adds the saturation flagging code.
The unit tests for the corresponding PR in JWST are passing : https://github.com/spacetelescope/jwst/pull/6317
=> adding common code for saturation

CHANGES.rst, src/stcal/dark_current/dark_class.py, src/stcal/dark_current/dark_sub.py, tests/test_dark_current.py, tests/test_dark_sub.py
This moves the dark current subtraction step to STCAL.  With a change in paths, the JWST unit tests pass.
=> JP-2310: Move dark current to STCAL

CHANGES.rst
=> changed changelog for 5.1, added entry

CHANGES.rst, src/stcal/ramp_fitting/gls_fit.py, src/stcal/ramp_fitting/ramp_fit_class.py, tests/test_ramp_fitting_gls_fit.py
Resolves [AL-579](https://jira.stsci.edu/browse/AL-579)
Closes #
This PR addresses problems computing final computations for multiple integrations.  This has been fixed and tests have been updated.
**Checklist**
=> AL-579: Updating GLS processing and fixed tests for multi-integrations.

CHANGES.rst, src/stcal/dark_current/dark_sub.py, src/stcal/jump/twopoint_difference.py, src/stcal/linearity/linearity.py, src/stcal/ramp_fitting/gls_fit.py, src/stcal/ramp_fitting/utils.py, tests/test_ramp_fitting_gls_fit.py
Resolves [JP-2796](https://jira.stsci.edu/browse/JP-2796)
Closes #
This PR addresses style issues related to flake8 error E275, as well as parentheses usage.
**Checklist**
=> JP-2796: Made style changes due to new flake8 5.0.3

src/stcal/ramp_fitting/ols_fit.py, tests/test_ramp_fitting.py
This PR makes small `ruff` fixes
**Checklist**
=> fix ruff errors

tox.ini
waiting on https://github.com/spacetelescope/stcal/actions/runs/4324843035/jobs/7550221263
**Checklist**
=> pass `CI` environment variable to `toxenv`

README.md
Closes #16 
Updating and expanding the README file.
**Checklist**
=> Updating and expanding the read me file.

asv.conf.json
Currently, the commits at https://spacetelescope.github.io/bench/stcal/ do not show a commit when clicked; this configuration change should fix that.
**Checklist**
=> [benchmarks] add commit URL for showing commits when clicked

setup.py
This PR is attempt 2 at the fix attempted by #199
**Checklist**
=> Add c99 flag for gcc try 2

CHANGES.rst, src/stcal/ramp_fitting/ols_fit.py, src/stcal/ramp_fitting/utils.py, tests/test_linearity.py
Resolves [JP-nnnn](https://jira.stsci.edu/browse/JP-nnnn)
Resolves [RCAL-nnnn](https://jira.stsci.edu/browse/RCAL-nnnn)
Closes #
This PR addresses ...
**Checklist**
=> Fix failures with numpy 2

CHANGES.rst, src/stcal/ramp_fitting/utils.py
another deprecation warning from the JWST test
**Checklist**
=> `numpy` 2.0: `np.NaN` -> `np.nan`

.github/workflows/build.yml, .github/workflows/ci.yml, docs/conf.py, src/stcal/alignment/util.py
This PR will update `stcal-alignment` with the latest changes from `main`.
**Checklist**
=> Stcal alignment updates.

CHANGES.rst
=> fix changelog entry date

CHANGES.rst
=> change log for release 1.6.1

pyproject.toml
Resolves [JP-nnnn](https://jira.stsci.edu/browse/JP-nnnn)
Resolves [RCAL-nnnn](https://jira.stsci.edu/browse/RCAL-nnnn)
Closes #
This PR addresses ...
</details>
=> temporarily point to gwcs main

changes/352.bugfix.rst, src/stcal/resample/resample.py, src/stcal/resample/utils.py, tests/data/nrcb5-wcs.asdf, tests/resample/conftest.py, tests/resample/helpers.py, tests/resample/test_resample.py
Resolves [JP-3907](https://jira.stsci.edu/browse/JP-3907)
Closes https://github.com/spacetelescope/jwst/issues/9246
This PR basically undoes changes introduced in https://github.com/spacetelescope/jwst/pull/7894. For more details, see https://github.com/spacetelescope/jwst/issues/9246
It also adds a unit tests that checks that surface brightness photometry shows an agreement between distorted (input) images and resampled (distortion-free) images regardless of the location of the "source" in the distorted image.
I expect numerous test failures in JWST pipeline that will need to be OKified.
`jwst` regression tests: https://github.com/spacetelescope/RegressionTests/actions/runs/13797969918
`romancal` regression tests: https://github.com/spacetelescope/RegressionTests/actions/runs/13797977338 …
=> Do not rescale resampled image intensities

.github/workflows/ci.yml, changes/346.general.rst
Resolves [SCSB-195](https://jira.stsci.edu/browse/SCSB-195)
this change should immediately let us know if a new Python version breaks `stcal`
</details>
=> test with latest supported version of Python

.github/dependabot.yml, .github/pull_request_template.md, .github/workflows/changelog.yml, .github/workflows/tests.yml, .pre-commit-config.yaml, README.md, pyproject.toml
uses a common `.pre-commit-config.yaml` with other repositories in pipeline dependencies
As of the creation of this PR, checks that would change any files are commented out.
</details>
=> consistent `pre-commit` config
