spacetelescope/stcal

setup.cfg

`astropy` requires `numpy>=1.17`. This PR brings `numpy` minimum version requirement to `astropy` level. Of course we cannot do that if the code here is using `numpy` features available in let's say `numpy>=1.18`.
CC: @nden @jdavies-st

Lower numpy version requirement

---

CHANGES.rst
src/stcal/ramp_fitting/constants.py
src/stcal/ramp_fitting/gls_fit.py
src/stcal/ramp_fitting/ols_fit.py
src/stcal/ramp_fitting/ramp_fit.py
src/stcal/ramp_fitting/utils.py

Ramp fitting code moved from JWST to STCAL.

Al-479: Add ramp fitting to STCAL

---

.github/workflows/ci.yml
.github/workflows/publish-to-pypi.yml
tox.ini

Fixes #20 
Fixes #18 
Fixes #3 
The `py38` and `coverage` tests were doing the same thing except one was reporting coverage, so I removed `py38` matrix element in the workflow.  Coverage still needs to be fixed, as we should be checking coverage based on running the `jwst` and `romancal` tests.  Issue filed.

Add pypi publish workflow and fix jwst CI

---

CHANGES.rst
src/stcal/ramp_fitting/constants.py
src/stcal/ramp_fitting/ols_fit.py
src/stcal/ramp_fitting/ramp_fit.py
src/stcal/ramp_fitting/utils.py

The DQ flags were originally defined in the JWST pipeline and defined globally.  The move to STCAL for ramp fitting to be used by multiple pipelines, there is a possibility the flags could be different.  To accommodate for this, DQ flags are now passed as a parameter to `ramp_fit` as a dictionary with five required keywords.

Al-522: Adding a DQ flags parameter to `ramp_fit` to make them pipeline indepedent

---

CHANGES.rst
src/stcal/ramp_fitting/constants.py
src/stcal/ramp_fitting/ols_fit.py

Ramp fitting multiprocessing is now working as it did in JWST 1.1.0 with the optional results bug detailed in JP-1926.  For JP-1926, the optional results product varies in size depending on the maximum number of segments.  When sliced results from each process was being reassembled into the final optional results product returned from ramp fitting, the maximum sizes per slice may be different, so this needed to be accounted for.
All unit tests pass on JWST.

JP-2037 and JP-1926: Fixing ramp fitting multiprocessing to work with new STCAL interface.

---

CHANGES.rst
src/stcal/linearity/linearity.py
tests/test_linearity.py

Adds common code for linearity correction (WIP)

common code for linearity correction

---

docs/stcal/package_index.rst
docs/stcal/ramp_fitting/description.rst
docs/stcal/ramp_fitting/index.rst

PR #59 changed the comptutation of VAR_POISSON due to negative median rates for a pixel.  This PR updates the documentation reflecting that.

AL-595: Changing Ramp Fitting Documentation

---

CHANGES.rst
src/stcal/ramp_fitting/ols_fit.py
tests/test_ramp_fitting.py

When computing a segment for a ramp if a group exists just before the zeroth group of the current segment and it is flagged only `JUMP_DET` it should be added to the beginning of the ramp segment for computation.  Previously any flagged groups got added back to the beginning of the ramp segment.  The segment mask now excludes any group not flagged with only `JUMP_DET`.
Two tests have been added to ramp fitting unit tests to test the above conditions.
#67

JP-2326: Fixed incorrect slope calculation

---

CHANGES.rst
src/stcal/ramp_fitting/ols_fit.py
tests/test_ramp_fitting.py

Changed how `fit_2_group` functions.  It improperly assumed if group 0 was flagged, then the flag was `SATURATED`, which also invalidates group 1.  It is possible for group 0 to be flagged such that group 1 contains valid data to be used during ramp fitting.  Now the function properly uses valid data in group 1, when valid, even if group 0 is flagged with a non-`SATURATED` flag.
A unit test was added to test the various possibilities for a 2 group ramp.  All unit tests in JWST and STCAL pass.
This PR addresses the the following JIRA ticket.
https://jira.stsci.edu/browse/JP-2346

JP-2346: Changed the 2 Group Ramp Special Case

---

CHANGES.rst
src/stcal/linearity/linearity.py
tests/test_linearity.py

If the linear term of the linearity coefficients = 0, then the correction wipes out the linearity corrected data. This PR puts in a check if the linear term = 0 (usually all the linearity coefficients = 0  in this case, but the most important one to check is the linear term) and sets the linearity corrections to values that do not change the data linear term = 1 all other terms = 0 and the DQ flag is set to NO_LIN_CORR.
Fixes [JP-2311](https://jira.stsci.edu/browse/JP-2311)

Check linearity coefficients for zero linear terms JP-2311

---

src/stcal/jump/twopoint_difference.py
tests/test_twopoint_difference.py

This PR takes the place of #71 with a more final version on a new branch. I will update this description later. 
Several fixes to jump detection including:
1. fixes to the computation of the median that is used to compute jump thresholds
2. fixing an error that was causing the largest difference ratio to be missed when comparing to the threshold to classify jumps, resulting in many jumps being missed
3. restructuring code and adding comments that describe each step
4. fixes an issue with MIRI 3 & 4 group integrations (link PR / issue here)

Changes to jump detection 

---

CHANGES.rst
src/stcal/ramp_fitting/gls_fit.py
src/stcal/ramp_fitting/ols_fit.py
src/stcal/ramp_fitting/ramp_fit.py
src/stcal/ramp_fitting/ramp_fit_class.py
src/stcal/ramp_fitting/utils.py
tests/test_ramp_fitting_gls_fit.py

Adding GLS back to the ramp fitting module.  It works as before the JWST refactor that began in February 2021.  This is a replacement PR for https://github.com/spacetelescope/stcal/pull/51.  Please refer to the old PR for historical comments.
The ramp fitting unit tests in both JWST and STCAL pass or are skipped/xfailed as expected.

AL-576: Adding GLS to ramp fitting.

---

CHANGES.rst
src/stcal/jump/twopoint_difference.py
tests/test_twopoint_difference.py

Fixes a small bug in the computation of the median for pixels with two usable diffs and no flagged groups. Also adds tests that cover this median function for all possible inputs. Adds in logging statements for two point difference routine. 
Additional fixes for [JP-2206](https://jira.stsci.edu/browse/JP-2206).

Jump step: fix median, add tests, add logging

---

CHANGES.rst
src/stcal/ramp_fitting/gls_fit.py
src/stcal/ramp_fitting/ols_fit.py
src/stcal/ramp_fitting/ramp_fit.py
src/stcal/ramp_fitting/ramp_fit_class.py
src/stcal/ramp_fitting/utils.py
tests/test_ramp_fitting.py

Resolves [JP-2071](https://jira.stsci.edu/browse/JP-2071)
A `suppress_one_group` boolean variable has been added as a parameter to the `ramp_fit` function.  
When true saturated ramps with only the 0th group being good will be treated as completely saturated ramps.  The calculations will be done as if all calculations are saturated, but the DQ flags will be set as if the first group is good, i.e., the pixel DQ will not have DO_NOT_USE set.
When false saturated ramps with only the 0th group being good will be treated as the normal special case of having only one good group.

JP-2071: Add feature to turn off calculations for saturated ramps with good 0th group

---

CHANGES.rst
src/stcal/jump/twopoint_difference.py

This PR fixes an issue where saturated pixels were also being flagged as jumps. While the initial pass to find jumps was correctly ignoring saturated and donotuse pixels, when the flag to set the DQ for neighboring pixels was set, if the neighboring pixels contained these flags the jump flag was simply added to them. Now, if a neighboring pixel is saturated or donotuse, it will not also be flagged as a jump.
Fixes [JP-2525](https://jira.stsci.edu/browse/JP-2525)

JP-2525: jump step flagging saturated groups as jumps

---

CHANGES.rst
setup.cfg
src/stcal/saturation/saturation.py
tests/test_saturation.py

Pixels adjacent to saturated pixels are now also flagged as saturated. By default, every pixel that touches the saturated pixels will also be flagged. The parameter 'n_pix_grow_sat' controls how many pixels out are also flagged, and this can also be set to 0.

JP-2556: Handle charge spilling out of saturated pixels into neighbors

---

src/stcal/jump/jump.py
src/stcal/jump/twopoint_difference.py

Fixes an issue in jump where the input gdq arrays were being modified which was causing tests to fail in JWST when the step was being run in multiprocessing mode. If multiple processes are run, the gdq/data arrays are copied before `find_crs` and not again within the function (which in this mode is running on slices).

JP-2581: fix to allow multiprocessing for jump

---

src/stcal/ramp_fitting/ramp_fit.py

This is a follow-up on #81 - adds a guard for "frame zero" , since Roman does not have one.

Frame zero in saturation correction - Roman does not have zero frame

---

CHANGES.rst
src/stcal/ramp_fitting/ramp_fit.py

Due to the possibility the first groups of a ramp could be flagged as DO_NOT_USE, as well as the way the jump detector works, the one good group suppression handler needed to be modified to handle these cases as well.

JP-2572: Updating the handler for the suppression of one good group ramps.

---

CHANGES.rst
src/stcal/ramp_fitting/gls_fit.py
src/stcal/ramp_fitting/ols_fit.py
src/stcal/ramp_fitting/ramp_fit.py
src/stcal/ramp_fitting/ramp_fit_class.py
src/stcal/ramp_fitting/utils.py
tests/test_ramp_fitting.py
tests/test_ramp_fitting_gls_fit.py

The multiprocessing feature of ramp fitting was failing.  To ensure new features worked properly with multiprocessing the unneeded one group suppression list got removed and the `ZEROFRAME` handling got moved to after multiprocessing to ensure proper usage.
The primary cause of the multiprocessing failure was the `int_times` object, which is an `astropy.io` object that cannot be properly pickled.  Since it is not used in ramp fitting, it is no longer passed to `STCAL` ramp fitting.

JP-2623: Fixing multiprocessing failure

---

CHANGES.rst
src/stcal/ramp_fitting/ols_fit.py
tests/test_ramp_fitting.py

Fully saturated exposures have no good data to process, so should return `NoneType` for all return variables.  The location for the full saturation check moved to before multiprocessing could take place.  This prevents the possibility of multiprocessing from computing ramp fitting for some data, but returning `NoneType` for data that just happens to be saturated after slicing up the data for multiprocessing.

JP-2651: Fully Saturated Exposures Should Return NoneType

---

CHANGES.rst
src/stcal/jump/jump.py
src/stcal/jump/twopoint_difference.py

Changing the normal rejection threshold parameter name in twopoint_difference to match what it is called elsewhere in jump step in jwst/roman

changing param name in jump twopoint_difference function

---

CHANGES.rst
src/stcal/ramp_fitting/gls_fit.py
tests/test_ramp_fitting_gls_fit.py

Resolves [JP-2378](https://jira.stsci.edu/browse/JP-2378)
Resolves [RCAL-nnnn](https://jira.stsci.edu/browse/RCAL-nnnn)
Closes #
This PR addresses a skipped test that crashed due to having an incorrect shape.  A saturated two group ramp caused an intermediate DQ array to have an incorrect shape.  Troubleshooting this I found small errors in computation due to bad variable names, like `gdq_cube` for a 4-D array.  The intermediate array shape error has been fixed, as well as the final DQ flags for ramps with saturated groups.
**Checklist**

JP-2378: A Two Group Saturated Ramp Crashed Due to Incorrect Ndarray Shape

---

CHANGES.rst
src/stcal/ramp_fitting/ols_fit.py
src/stcal/ramp_fitting/ramp_fit_class.py
src/stcal/ramp_fitting/utils.py
tests/test_ramp_fitting.py

Updating handling NaNs in the rateints product, as well as the DQ flags associated with those NaNs.
Resolves [JP-2669](https://jira.stsci.edu/browse/JP-2669)
Closes #
This PR addresses NaNs in the rateints product file and the DQ flags associated with them.  In the rateints product, NaNs were present with `Good` DQ flags.  They shouldn't be.  
Further, INS requested no NaNs be present in the rateints file.  This PR detects NaNs in the rateints file and sets them to 0.0, then sets the corresponding DQ flag to `DO_NOT_USE`.  
Lastly, the rateints DQ flags were set considering only `JUMP_DET` and `SATURATED`.  This has now been changed to consider `DO_NOT_USE` as well.  Specifically, if all groups in an integration for a pixel are flagged as DO_NOT_USE, the corresponding DQ value will be …

JP-2669: Fixing the NaN and DO_NOT_USE bug.

---

CHANGES.rst
src/stcal/ramp_fitting/gls_fit.py
tests/test_ramp_fitting.py
tests/test_ramp_fitting_gls_fit.py

Resolves [JP-2817](https://jira.stsci.edu/browse/JP-2817)
This PR addresses bad gain values.  Negative and NaN values should result in setting DQ flags for DO_NOT_USE and NO_GAIN_VALUE.  Also, NaN gain values results in NaNs in the final image product, which should not happen.  NaNs should be set to zero in the final image.
**Checklist**

JP-2817: GLS doesn't properly handle bad gain values

---

CHANGES.rst
src/stcal/jump/jump.py
src/stcal/jump/twopoint_difference.py
tests/test_twopoint_difference.py

Resolves [JP-2693](https://jira.stsci.edu/browse/JP-2693)
This PR implements the enhancement to the jump step where groups after detected ramps are flagged as jumps.  This "corrects" transients seen that make the slope after a jump different than before.  This PR allows for flagging to be different for two different jump thresholds.
**Checklist**

JP-2693: Flag groups do_not_use after detected ramp jumps

---

CHANGES.rst
src/stcal/jump/jump.py

Resolves [JP-2696](https://jira.stsci.edu/browse/JP-2696)
Closes https://github.com/spacetelescope/jwst/issues/6944
This PR addresses https://github.com/spacetelescope/jwst/issues/6944 - "Jump detection modifies input data by gain multiplier". In this step the data in the input object is multiplied by the gain (converting from DN to electrons) within the algorithm. This PR reconverts that data back to DN at the end of the step. This solves the user's problem of not being able to test multiple jump detection parameters using the same input.
**Checklist**

Jump modifies input data by gain multiplier (JP-2696).

---

.github/labeler.yml
.readthedocs.yaml
docs/conf.py

update the name of the ReadTheDocs configuration file to `.readthedocs.yaml` and add `nitpicky` and `fail_on_warning`
**Checklist**

use canonical filename of RTD configuration

---

CHANGES.rst
src/stcal/dark_current/dark_sub.py

Resolves [JP-2938](https://jira.stsci.edu/browse/JP-2938)
Closes #120 
This PR fixes a bug in the computation of the total number of data frames in science and dark ramps when nframes > 1 and/or groupgap > 0.
**Checklist**

JP-2938: Fix total frames computation in dark current

---

CHANGES.rst
src/stcal/jump/jump.py

Resolves [JP-2944](https://jira.stsci.edu/browse/JP-2944)
This PR addresses the fact that the new expansion of the shower ellipses in the JUMP step increases both the major and minor axis of the ellipse by the same relative factor. The change is to instead increase both axes by the same number of pixels. The new code changes the expansion along the major axis to be the same number of pixels as along the minor axis.
**Checklist**

JP-2944: Limit major axis expansion for MIRI shower flagging

---

CHANGES.rst
docs/stcal/ramp_fitting/description.rst
src/stcal/ramp_fitting/gls_fit.py
src/stcal/ramp_fitting/ols_fit.py
src/stcal/ramp_fitting/utils.py
tests/test_ramp_fitting.py
tests/test_ramp_fitting_gls_fit.py

Resolves [JP-2988](https://jira.stsci.edu/browse/JP-2988)
Closes #
This PR addresses setting the saturation flag.  In the rateints product, the saturation flag will only be set if the ramp for that pixel is fully saturated, i.e., saturation starts in group 0.  In the rate product, the saturation flag will only be set if the saturation flag is set for each integration.
**Checklist**

JP-2988: Set saturation only if fully saturated.

---

CHANGES.rst
pyproject.toml
src/stcal/jump/jump.py
tests/test_jump.py

Resolves [AL-691](https://jira.stsci.edu/browse/AL-691)
This PR removes unconditional dependency on `opencv-python` added in a previous PR; this was causing installation issues on some users' platforms.
I am also exploring replacing usage of `opencv-python` with `scikit-image`
**Checklist**

remove dependency on `opencv-python`

---

CHANGES.rst
docs/stcal/ramp_fitting/description.rst
src/stcal/ramp_fitting/ols_fit.py
src/stcal/ramp_fitting/utils.py
tests/test_ramp_fitting.py

Resolves [JP-3014](https://jira.stsci.edu/browse/JP-3014)
Closes #
This PR addresses invalid slope data found through flagging.  Specifically, pixels flagged as SATURATED or DO_NOT_USE have no valid data.  Currently, that data is set to zero, but zero can be valid data, so this data is not set NaN.
**Checklist**

JP-3014: This Sets Invalid Slope Data to NaN in the Rate and Rateints products.

---

.github/workflows/ci.yml
CHANGES.rst
pyproject.toml
src/stcal/jump/jump.py
tests/test_jump.py
tox.ini

Addresses https://github.com/spacetelescope/jwst/issues/7409
related to https://github.com/spacetelescope/jwst/pull/7414
This PR addresses the issue brought up in https://github.com/spacetelescope/jwst/issues/7409; a lack of specificity when using `jump.use_ellipses = True` without an `opencv` installation. Instead of a `UserWarning` being printed at import time, a `ModuleNotFoundError` is raised in runtime if ellipse functionality is selected and `opencv-python` is not detected.
```python
ELLIPSE_PACKAGE_WARNING = '`opencv-python` must be installed (`pip install stcal[opencv]`) in order to use ellipses'
```
**Checklist**

add specific exception when ellipse construction attempted without `opencv-python` installed

---

CHANGES.rst
src/stcal/ramp_fitting/utils.py

Resolves [JP-3044](https://jira.stsci.edu/browse/JP-3044)
This PR addresses the cast warning associated with ramp fitting in the function `dq_final_compress`.  The casting of the negation for the variable `not_sat_or_dnu` caused an overflow.  To fix this `dnu` and `sat` are now cast to `uint32` before the creation of the variable `not_sat_or_dnu`.
**Checklist**

JP-3044 (partial): Changing Cast to Eliminate Cast Warning.

---

CHANGES.rst
src/stcal/dark_current/dark_class.py

Resolves [JP-nnnn](https://jira.stsci.edu/browse/JP-nnnn)
Resolves [RCAL-438](https://jira.stsci.edu/browse/RCAL-438)
Closes #
This PR adds support for quantities within the dark class for Roman. Unit tested against both Roman & JWST.
**Checklist**

RCAL-438 Add support for Reference File Quantities

---

CHANGES.rst
src/stcal/ramp_fitting/ols_fit.py
src/stcal/ramp_fitting/ramp_fit.py
src/stcal/ramp_fitting/utils.py
tests/test_ramp_fitting.py

Resolves [JP-3004](https://jira.stsci.edu/browse/JP-3004)
This PR addresses zero values for suppressed ramps that should have been set to NaN in both the rate and rateints product.  There was an unexpected edge case due to the jump step setting JUMP_DET because of the `flag_4_neighbors` being set to true.  This resulted in an effective 2 group ramp with the second ramp being flagged as JUMP_DET, which is nonsense.   Further, in ramp fitting, because the `suppress_one_group` is set to true, this has the result in the first group being marked as DO_NOT_USE, while the second group is only a jump detection.  A one group ramp with the DO_NOT_USE flagged has different results to a one group ramp flagged as JUMP_DET, a situation unanticipated.
The solution was to suppress all groups in a one …

JP-3004: Should have NaN's for Suppressed Ramps, but Getting Zeros.

---

CHANGES.rst
src/stcal/ramp_fitting/ols_fit.py
src/stcal/ramp_fitting/ramp_fit_class.py
src/stcal/ramp_fitting/utils.py
tests/test_ramp_fitting.py

Resolves [JP-3077](https://jira.stsci.edu/browse/JP-3077)
This PR addresses the incorrect usage of group_time for ramps that have non-zero groupgap and the 0th group the only good group in the ramp.  Because of the readout pattern, the time for the 0th group alone is computed using `(NFrames+1)*TFrame/2`, instead.
This had similar computations for ZEROFRAME handling and was noted the use of for loops during computation, so an effort was made to use a numpy approach so that numpy will handle the for loops for performance reasons.
**Checklist**

JP-3077: Change the Computation in Ramps with only One Good Group in the 0th Group

---

tox.ini

jwst ignores the scripts directory for pytest
https://github.com/spacetelescope/jwst/blob/4285c4efb95bc368f36456e9e106e6aba6abd597/setup.cfg#L152
this PR replicates that ignore to allow the CI to pass
similar issues were found in other packages:
gwcs: https://github.com/spacetelescope/gwcs/pull/444
stpipe: https://github.com/spacetelescope/stpipe/pull/83
**Checklist**

to match jwst testing, ignore scripts in jwst ci job

---

CHANGES.rst
docs/stcal/ramp_fitting/description.rst
src/stcal/ramp_fitting/gls_fit.py
src/stcal/ramp_fitting/ols_fit.py
src/stcal/ramp_fitting/utils.py
tests/test_ramp_fitting.py

Resolves [JP-3132](https://jira.stsci.edu/browse/JP-3132)
Closes #152 
This PR addresses errors during processing when invoking multiprocessing requesting more processors than rows.  The data is sliced up by dividing the number of rows by the number of processors requested.  If the number of rows is less than the number of processors requested, this results in processors running on empty data sets with dimensions (nints, ngroups, 0, ncols).
To prevent this from occurring safeguards have been implemented in multiprocessing to prevent the usage of more processors than rows available.  The number of processors actually used will now be no more than the number of rows, regardless of the number of processors requested.
**Checklist**

JP-3132: Errors During Multiprocessing When More Processors are Requested than Rows in the Data

---

.github/workflows/ci.yml
.github/workflows/ci_cron.yml
CHANGES.rst
pyproject.toml
tox.ini

This PR abstracts CI workflows to the OpenAstronomy workflows; this should reduce maintenance for updating and maintaining actions. Additionally, these changes move the majority of MacOS jobs to the weekly scheduled workflow. This should alleviate the issue where the limited MacOS runners for the organization are not available for CI jobs.
**Checklist**

use OpenAstronomy workflows and move MacOS jobs to schedule

---

.github/workflows/ci.yml
CHANGES.rst
pyproject.toml
src/stcal/jump/jump.py
tests/test_jump.py
tox.ini

This PR reverts #126 and #136 and restores `opencv-python` to a hard dependency in the requirements; this will break certain external user workflows on platforms without a precompiled `opencv` available.
**Checklist**

restore `opencv-python` to a hard dependency

---

CHANGES.rst
src/stcal/ramp_fitting/ramp_fit.py

Closes https://github.com/spacetelescope/jwst/issues/7554
This PR addresses the missing `meta` tag from the attributes path checking for `drop_frame1`.  The attribute has been properly added.
**Checklist**

Adding proper 'meta' tag when checking for dropframe.

---

.github/workflows/ci.yml
.github/workflows/ci_cron.yml
.readthedocs.yaml
CHANGES.rst
docs/rtd_environment.yaml
pyproject.toml

Numpy is imminently dropping support for Python 3.8
**Checklist**

drop support for Python 3.8

---

CHANGES.rst
src/stcal/ramp_fitting/ols_fit.py
tests/test_ramp_fitting.py

Correcting the way the number of groups in a segment gets calculated for the optimal weighting during the weighted OLS fitting for each segment.
Resolves [JP-3221](https://jira.stsci.edu/browse/JP-3221)
This PR addresses the computation of segment lengths for the purposes of optimal weighting.  Originally, this was done by counting the non-zero groups in an integration ramp of the masked data.  The masked data was created by multiplying a boolean array where contiguous `True` values defined the current segment being computed.  This multiplication had the side effect that `np.nan * False = np.nan`, so NaN groups were incorrectly being included in the computation of the number of groups in a segment.
Specifically, a test ramp with the group DQ flags as follows:
GDQ: [0, 0, 0, 4, 0, 0, 0, 0, …

JP-3221: Fixing Segment Length Computation Needed for Optimal Weighting

---

pyproject.toml

Closes https://github.com/spacetelescope/stenv/issues/103
This PR tests replacing `opencv-python` with `opencv-python-headless`, a pre-built CPU-only binary, to resolve the issue raised in https://github.com/spacetelescope/stenv/issues/103
**Checklist**

replace `opencv-python` with pre-built CPU-only `opencv-python-headless`

---

CHANGES.rst
src/stcal/dark_current/dark_class.py
src/stcal/dark_current/dark_sub.py

Resolves [JP-3111](https://jira.stsci.edu/browse/JP-3111)
This PR updates the dark_sub routine to fix the way darks are subtracted from MIRI segmented data files. The integration-dependent darks should only be subtracted when processing the segment containing the first integrations in the exposure. All other segments just use the last dark integration. So a check has been added to the logic of choosing dark integrations to see if the science segment starts at integration 1.
**Checklist**

JP-3111: Fix dark subtraction for MIRI segmented data

---

.github/workflows/ci_cron.yml
tox.ini

Resolves [SCSB-69](https://jira.stsci.edu/browse/SCSB-69)
test against `pre` wheels of `astropy`, `scipy`, and `numpy` to ensure incoming issues are resolved
**Checklist**

test against pre-built binaries of `scipy` and `numpy`

---

CHANGES.rst
src/stcal/ramp_fitting/ols_fit.py
tests/test_ramp_fitting.py

Resolves [JP-3004](https://jira.stsci.edu/browse/JP-3004)
This PR addresses the computation of multi-integration data that has bad multiple integrations.  The final image slope calculations incorrectly used variances from unusable integrations as a part of the denominator sum.  Because of this the slope had smaller value than it should have.  These variances are now excluded from the denominator, correcting the "averaging" of usable integration slopes.
**Checklist**

JP-3004: Corrects the Final Slope Computation for Multi-Integration Data with Some Unusable Integrations

---

CHANGES.rst
src/stcal/ramp_fitting/ols_fit.py
src/stcal/ramp_fitting/utils.py
tests/test_ramp_fitting.py

Closes #168 
This PR addresses the usage of `np.where` and removes it where possible for performance reasons in the ramp fitting step.
**Checklist**

Issue-168: Updating Usage of 'np.where' Function

---

CHANGES.rst
src/stcal/ramp_fitting/ols_fit.py
src/stcal/ramp_fitting/ramp_fit_class.py
src/stcal/ramp_fitting/utils.py
tests/test_ramp_fitting.py

Resolves [JP-3242](https://jira.stsci.edu/browse/JP-3242)
This PR addresses special handling of timing for ramps that have only good 0th group in a ramp.  The addition of this special case only properly computed the variances.  The timing division for the final slope computation still used the group time, which is not correct for certain special cases.  All timing divisions have been pushed back to the segment calculations, so there is no longer one final divide.  There is also the further subset special case for only 0th good group with the use of ZEROFRAME.
**Checklist**

JP-3242: Proper Handling of Timing for Final Slope Computation for only 0th Good Group Ramps

---

tests/test_alignment.py

This PR addresses an issue when creating a WCS object for the tests.
The coordinates of the vertices of the bounding box region for the `WCS` object used in the tests were wrongly specified as the center of the pixels instead of the corner (as expected when calling `wcs_from_footprint`). This PR fixes the unit tests.
**Checklist**

Fix issue with bounding box when creating WCS for tests.

---

src/stcal/alignment/reproject.py
src/stcal/alignment/tests/test_reproject.py

Resolves [HLA-1096](https://jira.stsci.edu/browse/HLA-1096)
This PR adds the reproject function to the codebase. This code was based on a similar function for JWST. A main difference between the two is that this code assumes that we are using the high-level [WCS API](https://docs.astropy.org/en/latest/wcs/index.html#loading-wcs-information-from-a-fits-file). Several unit tests are also added for the case of inputted strings, array, as well as an expected failure. 
**Checklist**

HLA-1096: Added Reproject function

---

setup.py

The Jenkins build for JWST is now getting the error:
```
error: ‘for’ loop initial declarations are only allowed in C99 mode
```
when building `stcal`. It looks like someone turned of that flag for gcc there. This should add the flag in.
**Checklist**

Add c99 flag for gcc

---

CHANGES.rst
src/stcal/ramp_fitting/ols_fit.py
src/stcal/ramp_fitting/utils.py
tests/test_ramp_fitting.py

Resolves [JP-3368](https://jira.stsci.edu/browse/JP-3368)
Closes #203 
Closes #192 
This PR corrects the calculations of median rates and variance calculations.  These errors were found during the C implementation for special cases.
Originally, the median rates excluded SATURATED flagged groups, but should exclude DO_NOT_USE flagged groups as well.  This change affects slope and Poisson variance calculations.
Also, for invalid integrations, non-zero variances were computed, but they should be 0.0.  This had already been properly handled for slope calculations in a previous PR addressing JP-3004.  Unfortunately, improper calculation of rateints and rate variances continued. 
**Checklist**

JP-3368: Changing ramp_fit Median Rate and Variance Calculations

---

.github/workflows/publish-to-pypi.yml

Closes #200 
This PR attempts to build wheels using `cibuildwheel` for specific platforms
If we would like to use the [OpenAstronomy action](https://github-actions-workflows.openastronomy.org/en/stable/publish.html), we'll need the PyPI token (instead of the username and password)
**Checklist**

set `build_platform_wheels` to `true`

---

src/stcal/alignment/util.py

This PR addresses an error that was caused by an unknown python type provided in the docstring's returned type section.
**Checklist**

Fix docstring returned type issue.

---

.github/workflows/ci.yml
tox.ini

This PR addresses the issue where downstream `romancal` tests don't have WebbPSF data: https://github.com/spacetelescope/stcal/actions/runs/6331167369/job/17195146180?pr=196
**Checklist**

download WebbPSF data for downstream tests

---

.github/workflows/build.yml

This PR updates the build matrix to build wheels for more versions of Python (currently the `build` workflow only builds for Python 3.9)
**Checklist**

expand build matrix with more Python versions

---

.github/workflows/ci.yml
.github/workflows/ci_cron.yml
.github/workflows/data.yml

This PR attempts to resolve WebbPSF data caching issues by simplifying the data retrieval process and adding a scheduled workflow that keeps the WebbPSF data up-to-date. To update the WebbPSF data cache manually, add the `update webbpsf data` label to a PR
Also, renames toxenvs in the CI to be more explicit on their Python version in the status check display
**Checklist**

add data workflow to retrieve WebbPSF cache and rename toxenvs

---

CHANGES.rst
src/stcal/ramp_fitting/ols_cas22/_core.pxd
src/stcal/ramp_fitting/ols_cas22/_core.pyx
src/stcal/ramp_fitting/ols_cas22/_fit_ramps.pyx
src/stcal/ramp_fitting/ols_cas22/_fixed.pyx
src/stcal/ramp_fitting/ols_cas22/_pixel.pxd
src/stcal/ramp_fitting/ols_cas22/_pixel.pyx
src/stcal/ramp_fitting/ols_cas22_fit.py
tests/test_jump_cas22.py

Resolves [RCAL-702](https://jira.stsci.edu/browse/RCAL-702)
This PR resolves a massive memory spike as part of the solution to RCAL-702
**Checklist**

RCAL-702: Fix memory use issue for Cas22 jump detection

---

CHANGES.rst
src/stcal/ramp_fitting/ols_cas22/_core.pyx
src/stcal/ramp_fitting/ols_cas22/_fixed.pyx
src/stcal/ramp_fitting/ols_cas22/_pixel.pyx
tests/test_jump_cas22.py

This PR makes some adjustments to the jump detection algorithm so that it exactly detects the jumps detected in the simulated data.
**Checklist**

Resolve some bugs with the jump fitting algorithm

---

CHANGES.rst
tests/test_ramp_fitting_cases.py

Resolves [JP-3458](https://jira.stsci.edu/browse/JP-3458)
This PR addresses moves CI tests from JWST to STCAL.
This PR is in conjunction with https://github.com/spacetelescope/jwst/pull/8060, which removed these tests from JWST.
**Checklist**

JP-3458: Moving ramp_fit CI tests from JWST to STCAL.

---

.github/workflows/build.yml
.github/workflows/ci_cron.yml

I have noticed that pushing commits to branches with open PRs can cause huge delays in the build job completing. This is because there are no concurrency checks, meaning all the previously triggered jobs (by other pushes) all run to completion. I also noticed this for the weekly job, which can by special request be run on a PR too.
**Checklist**

Add concurrency cancels to build and weekly cron

---

CHANGES.rst

Resolves [JP-nnnn](https://jira.stsci.edu/browse/JP-nnnn)
Resolves [RCAL-nnnn](https://jira.stsci.edu/browse/RCAL-nnnn)
Closes #
This PR addresses ...
**Checklist**

Update CHANGES.rst to make it more obvious which versions of ramp fitting have been updated.

---

.github/workflows/changelog.yml
CHANGES.rst

This PR updates the CI to use a pre-built changelog workflow, which is functionally equivalent to the current one
**Checklist**

Update changlog CI to use a pre-built workflow.

---

CHANGES.rst
src/stcal/jump/jump.py
src/stcal/jump/twopoint_difference.py
tests/test_jump.py
tests/test_twopoint_difference.py

Resolves [JP-3521](https://jira.stsci.edu/browse/JP-3521)
Closes spacetelescope/jwst#8221
This PR addresses the different results return from the Jump step when switching from single core processing to multiprocessing. The main problem was caused by calculating the number of rows per slice using floating point division. This lead to some rows not getting processed. 
In addition, the 4 neighbor flagging in multiprocessing was adding the jump bit to pixels that were already flagged as do_not_use or saturated. 
**Checklist**

JP-3521: Fix jump multiprocessing error

---

CHANGES.rst
docs/stcal/ramp_fitting/description.rst

This PR partially resolves [JP-3525](https://jira.stsci.edu/browse/JP-3525) by making updates to the docs stored in stcal, in order to merge and sort out the info between the docs in jwst and stcal. Related updates will be made in jwst/docs. The vast majority of the high-level step information, especially those things that are JWST-specific, is being moved to jwst/docs, while the stcal/docs retain only low-level algorithmic information.
**Checklist**

JP-3525: Merge jump and ramp_fitting docs content with jwst docs

---

.github/workflows/ci.yml
CHANGES.rst
src/stcal/jump/jump.py
src/stcal/ramp_fitting/ols_fit.py

Python 3.12 added a warning when the `fork` method (default of linux) was used for multiprocessing if a process contains threads:
```
/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=2229) is multi-threaded, use of fork() may lead to deadlocks in the child.
```
This warning can be seen in the logs for one of the `devdeps` jobs that uses python 3.12:
https://github.com/spacetelescope/stcal/actions/runs/8110832059/job/22168896740#step:10:169
This PR switches the method to `forkserver` using a `get_context` (to only effect the calls on the context).
This PR will allow jwst to remove the global calls to `set_start_method` which as noted in https://github.com/spacetelescope/jwst/issues/8306 can lead to unexpected …

Use multiprocessing `get_context` and python 3.12

---

CHANGES.rst
src/stcal/ramp_fitting/utils.py
tests/test_ramp_fitting.py

Resolves [JP-3583](https://jira.stsci.edu/browse/JP-3583)
Closes spacetelescope/jwst#8373
This PR addresses an issue in the ramp_fitting routine where when finding the cosmic ray free segments of integrations. The code accumulates the non-CR groups using a counter. The problem is that this counter is a uint8 data type. Thus, once we get above 256 groups, it rolls over leading to only using a subset of the groups in the slope fit.
The solution was to change three variables from UINT8 to UINT16. This is big enough given the overall limit on the number of frames.
**Checklist**

JP-3583: Long integrations truncation in ramp fitting

---

CHANGES.rst
src/stcal/ramp_fitting/ols_cas22/_jump.pyx

The use of `sqrt` from libc results in a cast to/from `double` in the ols_cas22 ramp fitting (with jump detection). This can result in small numerical differences that lead to romancal regtests that passed on jenkins but failed locally (due to a single extra jump in one pixel).
This PR switches `sqrt` for `sqrtf` to keep the intermediate values as `float` which leads to (at the moment) the same failure locally and on jenkins (where `test_rampfit_step[spec_full]` fails with a single pixel difference):
```
{'arrays_differ': {"root['roman']['data']": {'abs_diff': <Quantity 1.9270487 DN / s>,
'n_diffs': 1,
'worst_abs_diff': {'index': (2798,
2758),
'value': <Quantity 1.9270487 DN / s>},
```
Regtest run here: 
https://plwishmaster.stsci.edu:8081/job/RT/job/Roman-Developers-Pull-Requests/681/ …

use sqrtf to avoid cast to double

---

CHANGES.rst
src/stcal/jump/jump.py
src/stcal/jump/twopoint_difference.py
tests/test_jump.py

Resolves [JP-3562](https://jira.stsci.edu/browse/JP-3562)
Closes spacetelescope/jwst#8333
This PR addresses several effects that lead to inaccurate flagging of showers. These change improve the estimate of the median difference by using all the integrations. It also masks reference pixels to avoid them being used in the convolution used to detect faint emission.
**Checklist**

JP-3562: Shower flagging enhancement

---

CHANGES.rst
src/stcal/ramp_fitting/ols_fit.py
tests/test_ramp_fitting.py

This PR addresses the issue in [JP-3463](https://jira.stsci.edu/browse/JP-3463) where the addition of an average dark current to the poisson variance calculation step results in incorrect SCI array values for NIRSpec.  This PR adjusts the method of dealing with negative slopes and all-zero variance special cases.  Tested against two sets of MIRI data and one set of NIRSpec, and is working as intended both with and without specifying the new parameter.
Resolves [JP-3463](https://jira.stsci.edu/browse/JP-3463)
**Checklist**

JP-3463: Fix poisson variance calculation

---

CHANGES.rst
src/stcal/jump/jump.py
src/stcal/jump/twopoint_difference.py

Resolves [JP-3623](https://jira.stsci.edu/browse/JP-3623) by catching a few runtime warnings in the jump step that were no longer caught after recent updates.
Closes spacetelescope/jwst#8483
**Checklist**

JP-3623: Catch Runtime warnings in jump step

---

.github/workflows/build.yml
CHANGES.rst
docs/stcal/ramp_fitting/description.rst
setup.py
src/stcal/ramp_fitting/ols_fit.py
src/stcal/ramp_fitting/ramp_fit.py
src/stcal/ramp_fitting/ramp_fit_class.py
src/stcal/ramp_fitting/src/slope_fitter.c
src/stcal/ramp_fitting/utils.py
tests/test_ramp_fitting.py
tests/test_ramp_fitting_cases.py

Resolves [JP-3121](https://jira.stsci.edu/browse/JP-3121)
The C implementation of ramp fitting is complete, with the exception of the special handling for CHARGELOSS processing of read noise.
All CI tests pass in both STCAL and JWST, with minor changes in JWST CI tests.  The JWST tests must be written to enforce type for data arrays.  I will open a corresponding JWST PR to account for this.
By default ramp fitting still runs the python code.  In `ols_fit.py`, there is a boolean variable that acts as a switch to run the python code or C code.  It is use_c here:
https://github.com/spacetelescope/stcal/blob/480cec0ff8b3946513fd41ea4172449f510687be/src/stcal/ramp_fitting/ols_fit.py#L662
If you want to run the C code, set this variable to True.
**Checklist**

JP-3121: initial Code to Implement C-Extensions for Ramp Fit

---

CHANGES.rst
pyproject.toml
src/stcal/ramp_fitting/src/slope_fitter.c

resolves [SCSB-155](https://jira.stsci.edu/browse/SCSB-155)
Numpy 2.0 is scheduled for release on June 19th. Due to the C ABI updates, Python projects that build C extensions are required to build against Numpy 2.0 in order to use Numpy 2.0 in runtime.
This is backwards-compatible with Numpy versions in runtime as far back as `1.26`
this PR pins `numpy>=2.0.0rc2` in `build-system.requires`
> [!NOTE]
> this PR was generated automatically by ``batchpr`` :robot:
**Checklist**

[SCSB-155] build with Numpy 2.0 release candidate

---

CHANGES.rst
src/stcal/ramp_fitting/ols_fit.py
src/stcal/ramp_fitting/ramp_fit.py
src/stcal/ramp_fitting/ramp_fit_class.py

Resolves [JP-3678](https://jira.stsci.edu/browse/JP-3678)
Closes #8618
This PR addresses an error in multiprocessing with the selection of the OLS_C algorithm.  The C extension flag was not properly passed to the sliced data when prepared for multiprocessing, so the old python code ran, even the the C extension was selected.  The C extension selection is now properly passed to the sliced data, so the C extension will be run when multiprocessing is selected.
**Checklist**

JP-3678: Ensure C extension works with multiprocessing

---

CHANGES.rst
src/stcal/ramp_fitting/src/slope_fitter.c

Resolves [JP-3678](https://jira.stsci.edu/browse/JP-3678)
This PR fixes the C implementation of the poisson variance calculations when provided an average dark current.  It ensures appropriate weighting of the average dark when the average ramp is negative (due to influence of very small segments on the simple average ramp calculation) and ensures that the variance is not set to zero whenever the average ramp is below zero.  Largely, it follows the same kind of modifications made to the python routine previously in https://github.com/spacetelescope/stcal/pull/255
**Checklist**

JP-3678: Fix C poisson variance calculation

---

tox.ini

The devdeps tests are failing due to a failure to find a `tweakreg` dependency:
https://github.com/spacetelescope/stcal/actions/runs/10099805963/job/27929757174
https://github.com/spacetelescope/stcal/blob/5fbabf672bc4f9a5c1eb522bc7b8896a6a5dfcc8/tox.ini#L65
This PR fixes the typo to use `tweakwcs` and installs it from git (as I don't believe pre-releases are common for `tweakwcs`).
**Checklist**

fix devdeps

---

CHANGES.rst
src/stcal/ramp_fitting/src/slope_fitter.c
tests/test_ramp_fitting.py

…eturned too early, so never decremented reference counts for python objects.
Resolves [JP-3698](https://jira.stsci.edu/browse/JP-3698)
Closes [jwst/#8680](https://github.com/spacetelescope/jwst/issues/8680)
Closes #276 
This PR addresses a memory leak found in the ramp fitting C-extension.  Added decrement reference counters to objects referenced that were passed from the python code.  These missing decrements meant that reference counts were not properly garbage collected.
Attached is a screen shot of the memory usage from `memray` demonstrating there is no memory leak.
**Checklist**

JP-3698: Fixed Memory Leak in Ramp Fitting C-Extension

---

changes/282.bugfix.rst
src/stcal/ramp_fitting/ols_fit.py

Resolves [JP-3664](https://jira.stsci.edu/browse/JP-3664)
Partially closes [jwst/#8580](https://github.com/spacetelescope/jwst/issues/8580)
This PR addresses a change in behavior for numpy 2.0: 
> arr.newbyteorder('S').byteswap(inplace=True)
> \>\>\> AttributeError: `newbyteorder` was removed from the ndarray class in NumPy 2.0. Use arr.view(arr.dtype.newbyteorder(order))' instead.
This PR implements the dtype method.
**Checklist**

JP-3664: Numpy 2.0 incompatibility with existing use of newbyteorder

---

changes/285.bugfix.rst
src/stcal/jump/jump.py

This PR fixes the mismatch in > vs >= operators described in the jump step by JP-3689.
**Checklist**

JP-3689: Fix logic operator

---

.gitignore
CHANGES.rst
changes/275.general.rst
src/stcal/ramp_fitting/ols_fit.py
src/stcal/ramp_fitting/ramp_fit.py
src/stcal/ramp_fitting/ramp_fit_class.py
src/stcal/ramp_fitting/src/slope_fitter.c
tests/test_ramp_fitting.py
tests/test_ramp_fitting_cases.py
tests/test_ramp_fitting_gls_fit.py

Resolves [JP-3669](https://jira.stsci.edu/browse/JP-3669)
Closes #8601
This PR addresses the read noise variance recalculation based on the CHARGELOSS flag.  This recalculation was in the JWST ramp fit step code, but that came with a performance hit and was unnecessarily complicated.  The recalculation has been implemented in the C extension code, simplifying the ramp fitting, as well as improving performance.
There is a corresponding JWST PR that removes the CHARGELOSS recalculation from the step code, as well as removes the corresponding test. https://github.com/spacetelescope/jwst/pull/8678
The regression tests pass, except for one test.  The test failure has been confirmed to be incorrect.  The regression test truth file for this test needs to be updated: …

JP-3669: Updating the C Extension to do CHARGELOSS Read Noise Recalculations

---

.pre-commit-config.yaml
pyproject.toml
tox.ini

Style checks (via pre-commit) have not been checking any files in this repo as part of the CI.
See this recent run on main:
https://github.com/spacetelescope/stcal/actions/runs/11017955113/job/30597119856#step:10:63
With all checks showing:
```
check for added large files..........................(no files to check)Skipped
```
If I run them locally I see a large number of automatic changes:
36 files changed, 1091 insertions(+), 942 deletions(-)
and even after these see 79 ruff errors, many from codespell and 6 from reporeview.
In an effort to check something this PR:
- fixes the `check-style` job to check files
- disables all failing ruff and pre-commit rules (maybe we can re-enable these one-by-one in follow-up PRs)
With this PR the checks run: …

Enable style checks

---

changes/298.general.rst
src/stcal/ramp_fitting/ramp_fit_class.py
src/stcal/ramp_fitting/src/slope_fitter.c
tests/test_ramp_fitting.py
tests/test_ramp_fitting_cases.py

Resolves [JP-3734](https://jira.stsci.edu/browse/JP-3734)
Closes #
This PR addresses default algorithm testing for ramp fitting.  The OLS_C algorithm is now the default algorithm for testing.
This PR also addresses a bug that resulted in incorrect attempts to do the CHARGELOSS recalculations when not needed, which would result in a crash when trying to dereference a `NULL` pointer for `rd->orig_gdq`.
The PR revealed another bug in the creation of the optional results product.  The arrays were being created using `PyArray_EMPTY`, which didn't initialize memory, so unused elements in some of the optional results product arrays were junk.  The creation function used now is `PyArray_ZEROS`, which initializes the array to zero.
- …

JP-3734: Changed Default CI Test Algorithm to OLS_C

---

.github/workflows/ci.yml
changes/297.general.rst
tox.ini

Currently downstream testing of jwst and romancal end up using the pyproject.toml in this repository for determining pytest configuration.
https://github.com/spacetelescope/stcal/actions/runs/11142379456/job/30965215790#step:10:107
This ends up with pytest using options in these downstream tests that differ from the options used by the downstream packages in their tests (when run in their own CI). This in turn results in lots of false failures in our downstream testing.
This PR changes how the jwst and romancal downstream tests to use the pytest options defined in the respective repositories.
- ``changes/<PR#>.general.rst``: …

Isolate jwst/romancal pytest configuration

---

changes/303.general.rst
pyproject.toml
src/stcal/ramp_fitting/src/slope_fitter.c

This PR prepares the ramp fitting C-extension for the upgrade to python 3.13.  This version of python added an exception to the `PyLong_AsLong` function if the `PyObject` passed to it is `NoneType`.  Now for two attributes of `RampData` that can be `NoneType` a check needs to be put in place guard against this exception.  The other attributes of `RampData` that are expected to be integer type should never be `NoneType`, so should raise an exception if they are.
</details>

Python 3.13 preparation for ramp fitting.

---

changes/307.apichange.0.rst
changes/307.apichange.1.rst
changes/307.apichange.rst
src/stcal/alignment/util.py
src/stcal/tweakreg/astrometric_utils.py
src/stcal/tweakreg/tweakreg.py
tests/test_alignment.py

Resolves [AL-837](https://jira.stsci.edu/browse/AL-837)
This PR simplifies the calculation of the output WCS for resample.  Previously, the `wcs_from_footprints` function accepted a list of WCS objects, one for each input model, and computed the footprints from those WCS objects to pass into `_calculate_new_wcs()`.  However, computing the footprints here is unnecessary because that information is already stored in the S_REGION keyword.  This PR makes `wcs_from_footprints` take in an actual footprint instead, in the form of either a numpy array or an S_REGION string.
This PR will require small changes to both jwst and romancal, both of which are using the `wcs_from_footprints` function.  I'm not sure there's a way to avoid that.  One other non-hidden function changed, `compute_fiducial`, …

AL-837: Calculate output WCS for resample from already-known s_region

---

src/stcal/outlier_detection/utils.py
tests/outlier_detection/test_utils.py

Resolves [AL-875](https://jira.stsci.edu/browse/AL-875)
This PR adds memory-saving options to a call to astropy `sigma clip` within `compute_weight_threshold` in an attempt to decrease the overall memory usage of outlier detection step (see flamegraphs on [JP-3685](https://jira.stsci.edu/browse/JP-3685)), which cause that function to modify the input array in-place instead of copying it and allocating extra arrays for masks.  Since the output sigma-clipped array is immediately collapsed into its mean, there is no need to retain it as a masked array and the behavior is unchanged.
Note that the "masked=False" option to sigma_clip does not affect that function's processing of _input_ masked arrays, it only specifies whether the _output_ is a masked array with clipped pixels masked, or a …

AL-875: Add memory saving options to compute_weight_threshold sigma_clip call

---

src/stcal/outlier_detection/utils.py
tests/outlier_detection/test_utils.py

Reverts spacetelescope/stcal#312
The reverted PR is causing regression test failures due in part to np.mean on a masked float32 array (which was the pre-PR behavior) producing a different result compared to a np.mean on a float32 array.

Revert "AL-875: Add memory saving options to compute_weight_threshold sigma_clip call"

---

changes/311.bugfix.rst
src/stcal/outlier_detection/utils.py
tests/outlier_detection/test_utils.py

Resolves [JP-3683](https://jira.stsci.edu/browse/JP-3683)
As part of outlier detection an "absolute derivative" is computed. From the [outlier detection docs](https://jwst-pipeline.readthedocs.io/en/latest/jwst/outlier_detection/outlier_detection_imaging.html):
```
The derivative of the blotted image gets created using the blotted median image to compute the absolute value of the difference between each pixel and its four surrounding neighbors with the largest value being the recorded derivative.
So in this case the "absolute derivative" is the maximum absolute difference between a pixel and it's neighbors.
```
This PR addresses 2 issues with `_abs_deriv` (used in outlier detection) where it:
- treated off-edge pixels as 0
- included `nan` values in the `max` used for combining …

JP-3683: fix abs_deriv handling of off-edge and nan values

---

tests/test_jump.py
tests/test_tweakreg.py

This PR adds the use of the [`tmp_path`](https://docs.pytest.org/en/stable/how-to/tmp_path.html#the-tmp-path-fixture) fixture so that the files generated by tests get cleaned up at the end of the test.
</details>

Clean up files generated by tests

---

changes/304.bugfix.rst
changes/318.bugfix.rst
src/stcal/ramp_fitting/ols_fit.py
src/stcal/ramp_fitting/src/slope_fitter.c
tests/test_ramp_fitting.py

Resolves [JP-3708](https://jira.stsci.edu/browse/JP-3708)
Resolves [JP-3771](https://jira.stsci.edu/browse/JP-3771)
Resolves [JP-3791](https://jira.stsci.edu/browse/JP-3791)
JP-3708: Add the CRMAG parameter to the optional results product in the C-extension.  This wasn't implemented with the C-extension, nor was it properly handled for multiprocessing.
JP-3771: Corrected bugs exposed by adding multiprocessing regression tests to the JWST regression testing suite.  The primary bug found was incorrect dimension sizes for internal arrays used for the optional results product.  The internal arrays should have dimensions of `(nints, nrows, ncols)`, but they had dimensions `(ngroups, nrows, ncols)`.  These incorrect dimensions caused memory corruption causing processes to freeze or segfault. …

JP-3708, JP-3771, JP-3791

---

changes/319.bugfix.rst
src/stcal/outlier_detection/utils.py
tests/outlier_detection/test_utils.py

This is "take 2" of https://github.com/spacetelescope/stcal/pull/312
At the moment this PR will create small numerical differences in the output of `compute_weight_threshold` but I'm convinced that the current behavior on main is incorrect and a by-product of related numpy bugs:
- https://github.com/numpy/numpy/issues/14462
- https://github.com/numpy/numpy/issues/25548
- https://github.com/numpy/numpy/issues/12313
A minimal example is:
```python
import numpy as np
one_f = np.float32(1)
s_f = np.spacing(one_f)
arr_f = np.array([one_f, one_f + s_f, one_f + s_f + s_f], dtype=np.float32)
one_d = np.float64(1)
arr_d = np.array([one_d, one_d + s_f, one_d + s_f + s_f], dtype=np.float64)
print(f"expected mean: {np.mean(arr_d)=}")
print(f"{np.mean(np.ma.array(arr_f, mask=False))=}") …
```

Weight threshold part duex

---

changes/314.bugfix.rst
pyproject.toml
src/stcal/alignment/util.py
tests/test_tweakreg.py

This is part of the work for AL-852: using the bounding_box in the inverse transforms.
It requires spacetelescope/gwcs#498 to be merged
Follow up PRs are spacetelescope/jwst#8554  and spacetelescope/romancal#1273
Closes #
This PR addresses ...
</details>

Inverse wcs bbox

---

pyproject.toml

Now that gwcs 0.22.0 is out we can remove the development dependency.
This updates the dependencies to use the new gwcs.
</details>

update gwcs dependency to released version, update other dependencies (to allow minimum deps to pass)

---

tests/test_tweakreg.py

There are failures detected by the CI when using the dev version of GWCS. These are due to an incorrect call to the GWCS API that happened to work before when constructing test data. This PR fixes that for the tests.
</details>

Fix wcs api call in tests

---

changes/333.bugfix.rst
src/stcal/tweakreg/tweakreg.py
tests/test_tweakreg.py

Resolves [JP-3686](https://jira.stsci.edu/browse/JP-3686)
Closes spacetelescope/jwst#8639
This PR allows the tweakreg step to parse absolute reference catalogs that resemble the output from the JWST `source_catalog` step.  That step reports absolute RA, DEC in columns called `sky_centroid.ra` and `sky_centroid.dec` which are parsed by into an astropy Table as a single column containing a SkyCoord.  This PR adds the functionality to re-cast this into RA/DEC columns as expected by `tweakwcs.align_wcs`.
</details>

JP-3686: Allow tweakreg to parse skycoord objects in absolute refcat

---

changes/334.apichange.rst
docs/stcal/jump/description.rst
src/stcal/dark_current/dark_class.py
src/stcal/dark_current/dark_sub.py
src/stcal/jump/jump.py
src/stcal/jump/jump_class.py
src/stcal/ramp_fitting/gls_fit.py
src/stcal/ramp_fitting/likely_algo_classes.py
src/stcal/ramp_fitting/ols_fit.py
src/stcal/ramp_fitting/ramp_fit.py
src/stcal/ramp_fitting/ramp_fit_class.py
src/stcal/ramp_fitting/src/slope_fitter.c
tests/test_dark_current.py
tests/test_jump.py
tests/test_ramp_fitting.py
tests/test_ramp_fitting_cases.py
tests/test_ramp_fitting_gls_fit.py
tests/test_ramp_fitting_likely_fit.py

Resolves [JP-3827](https://jira.stsci.edu/browse/JP-3827)
This PR removes references to the unused error array from the 4D ramp models. In the jwst pipeline, error values are not meaningful until after ramp fitting.
I also did a little minor cleaning for trivial things I noticed while making this change.  I'll note any significant differences.
Requires:
https://github.com/spacetelescope/stdatamodels/pull/384
https://github.com/spacetelescope/jwst/pull/9109
</details>

JP-3827: Remove unused error from ramp data

---

changes/337.general.rst
src/stcal/jump/jump.py
src/stcal/jump/twopoint_difference.py
tests/test_jump.py

Resolves [JP-3697](https://jira.stsci.edu/browse/JP-3697)
Closes #337
A number of changes to `twopoint_difference.py` and `jump.py` reduce memory usage by a factor of about 2 and improve runtime by a factor of anywhere from 3 to 20.  Tested output files (noted below) are unchanged, except for MIRI shower detection in `jw01701012001_02105_00001_mirifulong`.  This is due to a difference in replacing infilled saturated pixels after performing a convolution; the new version identifies fewer showers.  An example comment on this is here: 
https://jira.stsci.edu/browse/JP-3697?focusedId=760740&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-760740
Overflagging of jumps should no longer cause the pipeline to grind to a halt due to `np.where` combined with `for` …

Jump performance

---

changes/320.apichange.rst
docs/conf.py
docs/stcal/package_index.rst
docs/stcal/resample/description.rst
docs/stcal/resample/index.rst
docs/stcal/resample/utils.rst
pyproject.toml
src/stcal/resample/__init__.py
src/stcal/resample/resample.py
src/stcal/resample/utils.py
tests/resample/conftest.py
tests/resample/helpers.py
tests/resample/test_resample.py
tests/resample/test_resample_utils.py

Closes #279
This PR add the common resample code used by both JWST and Roman pipelines to stcal. Also, for the first time, this PR adopts the new `drizzle` API from https://github.com/spacetelescope/drizzle/pull/134 for the resample code used in the pipelines. This PR is a second attempt to #279 and therefore merging this PR should close #279.
This work is related to https://jira.stsci.edu/browse/AL-835
</details>

Add common resample code to stcal.

---

changes/338.bugfix.rst
src/stcal/jump/twopoint_difference.py
tests/test_jump_twopoint_difference.py

Resolves [JP-3793](https://jira.stsci.edu/browse/JP-3793) regarding inaccurate calculation of the number of groups in the jump step.  This PR updates prior https://github.com/spacetelescope/stcal/pull/317 to account for recent unrelated changes.
EDIT: See also [JP-3877](https://jira.stsci.edu/browse/JP-3877).  This PR ensures that long TSO exposures don't fall into the wrong processing type, reducing runtime from over an hour to about 1 minute in the example given there.

JP-3793: Fix numbers of flagged groups

---

changes/326.bugfix.rst
src/stcal/alignment/util.py
tests/test_alignment.py
tests/test_ramp_fitting_gls_fit.py

Resolves [JP-3824](https://jira.stsci.edu/browse/JP-3824)
`wcs_from_sregions` is used by `make_output_wcs` function in the JWST pipeline to compute output WCS of the resampled image for the `ResampleStep` . Currently `wcs_from_sregions` assigns a bounding box to the output WCS that is computed in the assumption that `crpix` is `(0, 0)` and it is not adjusted when `crpix` is provided by the user and when it is different from `(0, 0)`. This causes unit test failures in JWST pipeline when run with master branch of `gwcs` since now inverse WCS transforms check for bounding box.
A separate issue observed while working on this (which may or may not be an issue) is that currently `crpix` is considered 0-indexed while in FITS WCS standard it is 1-indexed.
<details><summary>news fragment change …

JP-3824: Fix a bug in wcs_from_sregions when crpix is provided

---

changes/310.general.rst
docs/conf.py
docs/stcal/package_index.rst
docs/stcal/skymatch/description.rst
docs/stcal/skymatch/index.rst
pyproject.toml
src/stcal/skymatch/__init__.py
src/stcal/skymatch/skyimage.py
src/stcal/skymatch/skymatch.py
src/stcal/skymatch/skystatistics.py

This PR pulls the common parts of skymatch from romancal and jwst into stcal to be shared.
Note, no tests are included because it is well tested by the step tests in both romancal and jwst.
</details>

Pull common parts of skymatch from romancal and jwst into stcal

---

changes/344.bugfix.rst
src/stcal/jump/twopoint_difference.py

Resolves [JP-3894](https://jira.stsci.edu/browse/JP-3894)
Closes #
This PR fixes a bug where, for iterative flagging of jumps in a pixel, NaN values were not ignored when determining the maximum value. This affects jump detection results for pixels with >=4 valid groups and with at least one NaN in the ramp or set of ramps (if there are multiple integrations).
</details>

Fixed argmax -> nanargmax

---

changes/350.bugfix.rst
src/stcal/jump/jump.py
src/stcal/ramp_fitting/ols_fit.py

Resolves [JP-3726](https://jira.stsci.edu/browse/JP-3726)
This PR addresses when running the detector 1 pipeline, "No space left on device" and "warnings.warn('resource_tracker: There appear to be %d '" warnings appeared.  On @melanieclarke's recommendation, I switched the multiprocessing from "forkserver" to "spawn" and those warnings disappeared.  
</details>

JP-3726: Resource Warnings when Using Multiprocessing

---

changes/355.bugfix.rst
src/stcal/tweakreg/tweakreg.py
tests/test_tweakreg.py

Provides bugfix for new feature introduced in [JP-3686](https://jira.stsci.edu/browse/JP-3686). See that issue's GitHub mirror at https://github.com/spacetelescope/jwst/issues/8639
This PR addresses a bug found in the new feature discussed on the ticket.  In short, `tweakwcs` expects the reference catalog to have `RA` and `DEC` columns (case-sensitive, all-caps) but the catalog parser was not converting those columns to uppercase.
The stcal changes are a one-liner, but the existence of the bug revealed that a test was needed that actually round-trips the output from the `SourceCatalogStep` into the `TweakRegStep`.  This is provided in https://github.com/spacetelescope/jwst/pull/9301.
- ``changes/<PR#>.apichange.rst``: change to …

Bugfix source catalog passed into tweakwcs

---

changes/357.jump.rst
docs/stcal/jump/description.rst
src/stcal/jump/twopoint_difference.py

Resolves [JP-3892](https://jira.stsci.edu/browse/JP-3892)
Closes #9207
This PR adds documentation for cross integration jump detection using sigma clipping when there are enough integrations, when `only_use_ints` is True or enough total groups across all integrations when False.
</details>

JP-3892: Adding Documentation for Cross Integration Jump Detection

---

src/stcal/alignment/util.py

Astropy has deprecated `isiterable`:
https://github.com/astropy/astropy/pull/18053
it's implementation is identical to `np.iterable`:
https://numpy.org/doc/1.23/reference/generated/numpy.iterable.html
This PR switches `isiterable` usage to `np.iterable`.
Romancal regtests all pass: https://github.com/spacetelescope/RegressionTests/actions/runs/14710781790
JWST regtests all pass: https://github.com/spacetelescope/RegressionTests/actions/runs/14711586754
</details>

replace astropy isiterable with np.iterable

---

changes/364.general.rst
src/stcal/resample/resample.py
tests/resample/test_resample.py

This PR attempts to treat the various variance arrays in resample more symmetrically while not changing the behavior very much.  The basic idea is that all of the different variance arrays should be resampled in the same way.  It simplifies the code somewhat and allows other variance arrays to be specified for resampling, without adding more code to stcal/resample.  It does this by extending the "enable_var" argument to talk a list of variance arrays that should be resampled, but retaining the current behavior when enable_var = True.
Currently all romancal and most jwst tests pass.  The two failing jwst tests involve tests that the resample does the right thing when enable_var is True and the ivm weight type is selected, but the images do not include the var_rnoise weight type needed for …

Generic variances

---

src/stcal/alignment/util.py

Resolves [RCAL-1054](https://jira.stsci.edu/browse/RCAL-1054)
This PR corrects the definition of pixel scale ratio as used in resampling of imaging data (NOTE: for JWST, spectral resampling may use opposite definition to the one used in imaging)
</details>

Update docs to reflect correct definition for pixel scale ratio

---

.github/workflows/ci.yml
pyproject.toml
tox.ini

This PR fixes the downstream jwst and romancal jobs by not running them in parallel. This will cause these jobs to take longer but will work around 2 issues:
- pytest-cov and pytest-xdist issue handling warnings: https://github.com/pytest-dev/pytest-cov/issues/693 (since jwst now [turns warnings into errors](https://github.com/spacetelescope/jwst/pull/9490))
- crds issues due to parallel reference file fetching: https://github.com/spacetelescope/crds/issues/930
There is also a somewhat related issue where stray files from opencv are also causing run files See https://github.com/spacetelescope/jwst/pull/9512 for more details but since the coverage configuration for the jwst job uses the pyproject.toml in this directly we need to duplicate those jwst changes here. jwst also either includes …

fix downstream by not running in parallel

---

changes/385.general.rst
docs/stcal/package_index.rst
docs/stcal/velocity_aberration.rst
src/stcal/velocity_aberration.py
tests/test_velocity_aberration.py

Resolves [RCAL-1123](https://jira.stsci.edu/browse/RCAL-1123)
Required by romancal [PR#1891](https://github.com/spacetelescope/romancal/pull/1891)
This PR implements the common base velocity aberration calculation used by the command `roman_set_velocity_aberration`. 
</details>

add velocity aberration calculations
